In [18]:
import pandas as pd

In [19]:
msp_bd = pd.read_feather("/shared/projects/mudis4ls_is4_benchmark/BDs/hs_10_4_gut/database/hs_10_4_gut_1990MSPs_gtdb_r220.feather")

In [20]:
msp_bd

,msp_name,gtdb_r220_classification,superkingdom,phylum,class,order,family,genus,species,msp
0,msp_0001,d__Eukaryota;p__Heterokonta;c__Blastocystae;o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 3,msp_0001
1,msp_0002,d__Eukaryota;p__Heterokonta;c__Blastocystae;o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 1,msp_0002
2,msp_0003,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides cellulosilyticus,msp_0003
3,msp_0004,d__Eukaryota;p__Heterokonta;c__Blastocystae;o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 2,msp_0004
4,msp_0005,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Escherichia,Escherichia coli,msp_0005
...,...,...,...,...,...,...,...,...,...,...
1985,msp_2196,d__Bacteria;p__Bacillota_A;c__Clostridia;o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Acutalibacteraceae,Eubacterium_R,Eubacterium_R sp014465955,msp_2196
1986,msp_2207,d__Bacteria;p__Bacillota_A;c__Clostridia;o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Butyricicoccaceae,Butyricicoccaceae SIG471,Butyricicoccaceae SIG471 sp905199135,msp_2207
1987,msp_2209,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Succinivibrionaceae,Succinatimonas,Succinatimonas sp905203285,msp_2209
1988,msp_2210,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides sp. bacterium,msp_2210
1989,msp_2211,d__Bacteria;p__Bacillota_A;c__Clostridia;o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Ruminococcaceae,Ruminococcaceae FB2012,Ruminococcaceae FB2012 sp900539835,msp_2211

In [21]:
#Remplacer ; par |
msp_bd["gtdb_r220_classification"] = msp_bd["gtdb_r220_classification"].str.replace(";", "|", regex=False)

In [22]:
msp_bd

,msp_name,gtdb_r220_classification,superkingdom,phylum,class,order,family,genus,species,msp
0,msp_0001,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 3,msp_0001
1,msp_0002,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 1,msp_0002
2,msp_0003,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides cellulosilyticus,msp_0003
3,msp_0004,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 2,msp_0004
4,msp_0005,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Escherichia,Escherichia coli,msp_0005
...,...,...,...,...,...,...,...,...,...,...
1985,msp_2196,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Acutalibacteraceae,Eubacterium_R,Eubacterium_R sp014465955,msp_2196
1986,msp_2207,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Butyricicoccaceae,Butyricicoccaceae SIG471,Butyricicoccaceae SIG471 sp905199135,msp_2207
1987,msp_2209,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Succinivibrionaceae,Succinatimonas,Succinatimonas sp905203285,msp_2209
1988,msp_2210,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides sp. bacterium,msp_2210
1989,msp_2211,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Ruminococcaceae,Ruminococcaceae FB2012,Ruminococcaceae FB2012 sp900539835,msp_2211

In [23]:
meteor_output=pd.read_csv("/shared/projects/mudis4ls_is4_benchmark/test_results/meteor/profile/ERS12377136/ERS12377136_msp.tsv",sep="\t")

In [24]:
meteor_output

      msp_name  value
0     msp_0001    0.0
1     msp_0002    0.0
2     msp_0003    0.0
3     msp_0004    0.0
4     msp_0005    0.0
...        ...    ...
1985  msp_2196    0.0
1986  msp_2207    0.0
1987  msp_2209    0.0
1988  msp_2210    0.0
1989  msp_2211    0.0

[1990 rows x 2 columns]

In [25]:
meteor_output=meteor_output.merge(msp_bd)

In [26]:
meteor_output

,msp_name,value,gtdb_r220_classification,superkingdom,phylum,class,order,family,genus,species,msp
0,msp_0001,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 3,msp_0001
1,msp_0002,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 1,msp_0002
2,msp_0003,0.0,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides cellulosilyticus,msp_0003
3,msp_0004,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 2,msp_0004
4,msp_0005,0.0,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Escherichia,Escherichia coli,msp_0005
...,...,...,...,...,...,...,...,...,...,...,...
1985,msp_2196,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Acutalibacteraceae,Eubacterium_R,Eubacterium_R sp014465955,msp_2196
1986,msp_2207,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Butyricicoccaceae,Butyricicoccaceae SIG471,Butyricicoccaceae SIG471 sp905199135,msp_2207
1987,msp_2209,0.0,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Succinivibrionaceae,Succinatimonas,Succinatimonas sp905203285,msp_2209
1988,msp_2210,0.0,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides sp. bacterium,msp_2210
1989,msp_2211,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Ruminococcaceae,Ruminococcaceae FB2012,Ruminococcaceae FB2012 sp900539835,msp_2211

In [27]:
meteor_output=meteor_output.rename(columns={"value":"meteor_abundance"})

In [28]:
meteor_output

,msp_name,meteor_abundance,gtdb_r220_classification,superkingdom,phylum,class,order,family,genus,species,msp
0,msp_0001,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 3,msp_0001
1,msp_0002,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 1,msp_0002
2,msp_0003,0.0,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides cellulosilyticus,msp_0003
3,msp_0004,0.0,d__Eukaryota|p__Heterokonta|c__Blastocystae|o_...,Eukaryota,Heterokonta,Blastocystae,Blastocystida,Blastocystidae,Blastocystis,Blastocystis sp. subtype 2,msp_0004
4,msp_0005,0.0,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Escherichia,Escherichia coli,msp_0005
...,...,...,...,...,...,...,...,...,...,...,...
1985,msp_2196,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Acutalibacteraceae,Eubacterium_R,Eubacterium_R sp014465955,msp_2196
1986,msp_2207,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Butyricicoccaceae,Butyricicoccaceae SIG471,Butyricicoccaceae SIG471 sp905199135,msp_2207
1987,msp_2209,0.0,d__Bacteria|p__Pseudomonadota|c__Gammaproteoba...,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Succinivibrionaceae,Succinatimonas,Succinatimonas sp905203285,msp_2209
1988,msp_2210,0.0,d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides sp. bacterium,msp_2210
1989,msp_2211,0.0,d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...,Bacteria,Bacillota_A,Clostridia,Oscillospirales,Ruminococcaceae,Ruminococcaceae FB2012,Ruminococcaceae FB2012 sp900539835,msp_2211

In [29]:
meteor_output=meteor_output[["gtdb_r220_classification","meteor_abundance"]]

In [32]:
meteor_output = meteor_output[meteor_output["meteor_abundance"] != 0.0]

In [33]:
meteor_output

                               gtdb_r220_classification  meteor_abundance
6     d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...          0.022924
8     d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...          0.011958
11    d__Bacteria|p__Bacteroidota|c__Bacteroidia|o__...          0.016823
16    d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...          0.037285
17    d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...          0.015694
...                                                 ...               ...
730   d__Bacteria|p__Bacillota_A|c__Clostridia|o__Mo...          0.004740
735   d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...          0.006924
981   d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...          0.005266
1027  d__Bacteria|p__Bacillota_A|c__Clostridia|o__TA...          0.016690
1783  d__Bacteria|p__Bacillota_A|c__Clostridia|o__Os...          0.067027

[67 rows x 2 columns]

In [14]:
mpa_sylph_motus=pd.read_csv(
    "/shared/projects/mudis4ls_is4_benchmark/test_results/compare_mpa_sylph/compare_mpa_sylph.tsv",
    sep="\t"
    )

In [15]:
mpa_sylph_motus

,clade_name,abundance_metaphlan,abundance_sylph,abundance_motus
0,d__Bacteria,100.00000,100.0000,0.731786
1,d__Bacteria|p__Bacillota,NaN,NaN,0.401600
2,d__Bacteria|p__Bacillota_A,43.38615,41.4963,NaN
3,d__Bacteria|p__Bacillota_A|c__Clostridia,43.38615,41.4963,NaN
4,d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...,23.22263,24.1255,NaN
...,...,...,...,...
183,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
184,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
185,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
186,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
187,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538

In [16]:
mpa_sylph_motus=mpa_sylph_motus.rename(columns={"clade_name":"gtdb_r220_classification"})

In [17]:
mpa_sylph_motus

,gtdb_r220_classification,abundance_metaphlan,abundance_sylph,abundance_motus
0,d__Bacteria,100.00000,100.0000,0.731786
1,d__Bacteria|p__Bacillota,NaN,NaN,0.401600
2,d__Bacteria|p__Bacillota_A,43.38615,41.4963,NaN
3,d__Bacteria|p__Bacillota_A|c__Clostridia,43.38615,41.4963,NaN
4,d__Bacteria|p__Bacillota_A|c__Clostridia|o__La...,23.22263,24.1255,NaN
...,...,...,...,...
183,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
184,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
185,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
186,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538
187,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538

In [34]:
mpa_sylph_motus_meteor=mpa_sylph_motus.merge(meteor_output,how='outer')

In [35]:
mpa_sylph_motus_meteor

,gtdb_r220_classification,abundance_metaphlan,abundance_sylph,abundance_motus,meteor_abundance
0,d__Bacteria,100.00000,100.0000,0.731786,NaN
1,d__Bacteria|p__Actinomycetota|c__Coriobacterii...,NaN,NaN,NaN,0.006384
2,d__Bacteria|p__Actinomycetota|c__Coriobacterii...,NaN,NaN,NaN,0.006947
3,d__Bacteria|p__Bacillota,NaN,NaN,0.401600,NaN
4,d__Bacteria|p__Bacillota_A,43.38615,41.4963,NaN,NaN
...,...,...,...,...,...
225,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538,NaN
226,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538,NaN
227,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538,NaN
228,d__Bacteria|p__Verrucomicrobia|c__Verrucomicro...,NaN,NaN,0.019538,NaN
229,d__Bacteria|p__Verrucomicrobiota|c__Verrucomic...,NaN,NaN,NaN,0.010734

In [36]:
mpa_sylph_motus_meteor.to_csv("/shared/projects/mudis4ls_is4_benchmark/test_results/compare_outputs/mpa_sylph_motus_meteor.tsv", sep="\t")