In [1]:
import pandas as pd

# ðŸ“Œ Charger le fichier TSV
df = pd.read_csv("/shared/projects/mudis4ls_is4_benchmark/test_results/kraken/gtdb/test_Species.bracken", sep="\t")

In [2]:
df

,name,taxonomy_id,taxonomy_lvl,kraken_assigned_reads,added_reads,new_est_reads,fraction_total_reads
0,Bacteroides stercoris,46506,S,3744,2,3746,0.07276
1,Bacteroides uniformis,820,S,2991,0,2991,0.05809
2,Bacteroides xylanisolvens,371601,S,1448,0,1448,0.02812
3,Bacteroides finegoldii,338188,S,994,0,994,0.01931
4,Bacteroides ovatus,28116,S,794,0,794,0.01542
...,...,...,...,...,...,...,...
1077,Methanolobus mangrovi,3072977,S,1,0,1,0.00002
1078,Homo sapiens,9606,S,5,0,5,0.00010
1079,Junduvirus communis,2956034,S,10,0,10,0.00019
1080,Junduvirus copri,2956035,S,1,0,1,0.00002
1081,Parabacteroides phage YZ-2015a,1655644,S,1,0,1,0.00002

In [3]:
# ðŸ“Œ Filtrer les lignes oÃ¹ "name" est dupliquÃ©
df_duplicates = df[df.duplicated(subset=["name"], keep=False)][["name", "taxonomy_id"]]

# ðŸ“Œ Afficher les rÃ©sultats
print(df_duplicates)

# ðŸ“Œ Sauvegarder dans un fichier si besoin
# df_duplicates.to_csv("duplicates.tsv", sep="\t", index=False)

Empty DataFrame
Columns: [name, taxonomy_id]
Index: []